[package]
name = "rlab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
rand = "0.8.3"
twitter-v2 = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"
